#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Kenny Gorman

# Short bio or description (displayed in the header)
description: The love of Data, Database Engineering, Architecture, Entrepreneurship, and other assorted bits
url: http://www.kennygorman.com

excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty
baseurl:          /
title: 		      kennygorman.com

author:
  name:           'Kenny Gorman'
  url:            https://twitter.com/kgorman

paginate:         12

markdown:         kramdown
highlighter:      rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
permalink: /:title

# The release of Jekyll Now that you're using
version: 3.3

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

gems:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-paginate
